# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc529cd254b47a0c0cb70b0ce6b1784fece2ed7df1bd27ab69e1c0eeea3c19e93cfc2ee77787a0e8dc6e087ec8a91dd11ef7e27b976257d11d838ef320d70c86

test:
  secret_key_base: 7572979b3e3a8cc43b55c60cc4f3d88a058035647b28c83c5e27bad8c2c7b63a77de573be0ea7f150e02b7049e3d6a3ea66083eddc2bc37101ef6a15f4cfa8bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
